services:
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service:dev
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/hexagonal_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql-db
    networks:
      - user-network

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: hexagonal_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - user-network

volumes:
  mysql_data:

networks:
  user-network:
    driver: bridge
